In [1]:
import numpy as np

# NumPy — Arrays y operaciones numéricas

## Creación de arrays

Recordamos que NumPy gira alrededor de una estructura clara: el array. Parecido a una lista de Python pero más potente

In [ ]:
a = np.array([1,2,3,4,5]) # array de una dimensión
print(a)

[1 2 3 4 5]


In [ ]:
print(type(a)) # tipo del objeto

<class 'numpy.ndarray'>


ndarray significa N-dimensional array. Puede tener 1, 2, 3 o más dimensiones

In [ ]:
print(a.shape) # dimensión array
print(a.dtype) # tipo de datos en el objeto

(5,)
int64


(5,) significa 1 dimensión con 5 elementos. int64 es el tipo de dato: enteros de 64 bits.

In [ ]:
b = np.array([[1,2,3],[4,5,6]]) # array de dos dimensiones : matriz con 2 filas y 3 columnas. Pones dentro por filas
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
print(b.shape)

(2, 3)


In [ ]:
print(b.ndim) # numero de dimensiones-> dos
print(b.size) # numero de datos en el array

2
6


Por ahora, hemos usado la funcion array() para crear arrays de una dimension como [1,2] o de dos dimensiones como [[1,2],[3,4]]. El atributo shape para ver número de filas y de columnas, ndim para ver el número de dimensiones del array y size para ver el número de datos dentro del array.

Vemos otras formas de crear los arrays, de manera no tan directa

In [ ]:
c = np.zeros((3,4)) # llenar el array de ceros
print(c)

print(np.ones((2,4))) # y de unos 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(np.arange(0,10,2)) # del 0 al 10 dame numeros de 2 en 2

[0 2 4 6 8]


In [ ]:
print(np.linspace(0,1,5)) # del 0 y 1 dame 5 numeros espaciados igual

[0.   0.25 0.5  0.75 1.  ]


linspace divide un intervalo en partes iguales.

np.linspace(0, 1, 5) significa: dame 5 números entre 0 y 1 espaciados igual.

Resultado: [0, 0.25, 0.5, 0.75, 1.0]

La diferencia con arange es que en arange tú controlas el paso, en linspace tú controlas cuántos números quieres.

In [103]:
a_random = np.random.randint(0,100,size=(4,5)) # array random 

print(a_random)

[[74 98 89 15 13]
 [58  6 47 28 72]
 [77 42 93 26 76]
 [61 23 78 87 11]]


## Indexing y Slicing

Indexing — acceder a un elemento concreto por su posición. Como decir "dame el elemento de la fila 0, columna 2".

Slicing — coger un trozo del array. Como decir "dame todas las filas de la columna 1" o "dame desde la columna 1 hasta el final".

In [27]:
# se ha creado b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# accedemos a elementos del array de dos dimensiones
print(b[0]) # primera fila
print(b[1]) # segunda fila 

[1 2 3]
[4 5 6]


In [30]:
print(b[0,2]) # fila 0 columna 2-> me espero 3

3


In [33]:
print(b[:,1]) # todas las filas columna 1 (parecido a lo anterior pero con : para referirse a todas las filas)

[2 5]


In [34]:
print(b[0,1:]) # la fila 0 desde la columna 1 a todo lo demas 

[2 3]


## Operaciones matemáticas con arrays

In [36]:
print(a)

[1 2 3 4 5]


In [ ]:
print(a + 10)

print(a * 2)

print(a ** 2) # estamos elevando cada elemento 

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [42]:
# nuevo array 
d = np.array([10,20,30,40,50])
print(d)

[10 20 30 40 50]


In [41]:
print(a + d)
print(a * d)

[11 22 33 44 55]
[ 10  40  90 160 250]


In [47]:
# funciones estadisticas sobre a 
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a))

3.0
1.4142135623730951
1
5
15


In [48]:
print(b)

[[1 2 3]
 [4 5 6]]


In [52]:
print(np.mean(b)) # todos los elementos de la matriz-> no es interesante
print(np.sum(b)/b.size)

3.5
3.5


In [53]:
print(np.mean(b,axis = 0)) # media por columnas

[2.5 3.5 4.5]


In [55]:
print(np.mean(b,axis = 1)) # media por filas 

[2. 5.]


## Reshape

Reshape es cambiar la forma del array sin cambiar los datos. Por ejemplo, un array de 12 elementos lo puedes reorganizar como una matriz de 3x4, o de 2x6, o de 4x3 — siempre que el total de elementos sea el mismo.

In [ ]:
a = np.arange(1,13) # es como poner .arange(1,13,1)

print(a)
print(a.shape) # un vector 

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [61]:
b = a.reshape(3,4)

print(b)
print(b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [63]:
c = a.reshape(2,6)

print(c)
print(c.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [64]:
d= a.reshape(4,3)

print(d)
print(d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


## Funciones útiles

In [67]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [68]:
resultado = np.where(a>3,'grande', 'pequeño')
print(resultado)

['pequeño' 'pequeño' 'pequeño' 'grande' 'grande' 'grande']


In [69]:
c = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
print(c)

[3 1 4 1 5 9 2 6 5 3]


In [ ]:
print(np.unique(c)) # se queda con los unicos
print(np.sort(c)) # de menor a mayor queda ordenado

[1 2 3 4 5 6 9]
[1 1 2 3 3 4 5 5 6 9]


## Broadcasting

In [73]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print(a)
print(b)

print(a + b)

[[1 2 3]
 [4 5 6]]
[10 20 30]
[[11 22 33]
 [14 25 36]]


numpy "expande" automáticamente el array pequeño para operar con el grande, sin necesidad de duplicarlo manualmente.
Es muy útil para operaciones como normalizar datos, restar la media, etc.

## Ejercicios NumPy

### Ejercicio 1 — Creación
Crea un array de 10 ceros, luego uno de 10 unos y luego uno con los números pares del 0 al 20.

In [75]:
# import numpy as np
array_ceros = np.zeros(10)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [76]:
array_unos = np.ones(10)
print(array_unos)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [77]:
array_pares = np.arange(0,20,2)
print(array_pares)

[ 0  2  4  6  8 10 12 14 16 18]


### Ejercicio 2 — Shape y dimensiones
Crea una matriz de 4x5 rellena de unos. Comprueba su shape, ndim y size.

In [79]:
matriz_unos = np.ones((4,5))
print(matriz_unos)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [80]:
matriz_unos.shape

(4, 5)

In [81]:
matriz_unos.ndim

2

In [82]:
matriz_unos.size

20

### Ejercicio 3 — Indexing
Dado el array `a = np.arange(1, 26).reshape(5, 5)`, accede a:
- El elemento de la fila 2, columna 3
- Toda la tercera columna
- Las dos primeras filas completas

In [87]:
a = np.arange(1,26).reshape(5,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [88]:
print(a[1,2])

8


In [90]:
print(a[:,2])

[ 3  8 13 18 23]


In [93]:
print(a[:2,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Ejercicio 4 — Operaciones matemáticas
Dado `a = np.array([4, 16, 25, 36, 64])`, calcula la raíz cuadrada de cada elemento y suma todos los resultados.

In [98]:
a = np.array([4,16,25,36,64])

resultado = np.sqrt(a).sum()

print(resultado)

25.0


In [99]:
a = np.array([4,16,25,36,64])

resultado = np.sum(np.sqrt(a))

print(resultado)

25.0


### Ejercicio 5 — Estadística
Dado `a = np.random.randint(0, 100, size=(4, 5))`, calcula la media, máximo y mínimo de todo el array, luego la media por filas y por columnas.

In [ ]:
a = np.random.randint(0,100,size=(4,5)) # array random 

print(a)

[[45 22 46 94 22]
 [21 34 28 73 33]
 [70 26  4  8 28]
 [33 26  2 32 18]]


In [112]:
print(np.mean(a))
print(np.max(a))
print(a.min())
print(np.mean(a,axis=0)) # por columnas
print(np.mean(a,axis=1)) # por columnas

33.25
94
2
[42.25 27.   20.   51.75 25.25]
[45.8 37.8 27.2 22.2]


### Ejercicio 6 — Reshape
Crea un array del 1 al 24 y transfórmalo en una matriz de 3D con forma (2, 3, 4).

In [ ]:
array_1_24 = np.arange(1,25) # oones 25 para q sea hasta el 24
print(array_1_24)

array_1_24_reshape = np.reshape(array_1_24, (2,3,4))

print(array_1_24_reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [122]:
array_1_24_reshape = array_1_24.reshape(2,3,4)

print(array_1_24_reshape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### Ejercicio 7 — where
Dado `a = np.random.randint(0, 100, size=10)`, sustituye todos los valores mayores de 50 por 1 y el resto por 0.


In [123]:
a = np.random.randint(0,100, size= 10)

print(a)

[ 2 99 69 25 20  9 96 22  7 27]


In [125]:
resultado = np.where(a>50, 1, 0)

print(resultado)

[0 1 1 0 0 0 1 0 0 0]


### Ejercicio 8 — Broadcasting
Crea una matriz de 3x3 con valores del 1 al 9 y réstale a cada fila el array `[1, 2, 3]`.

In [135]:
matriz_1_9 = np.arange(1,10).reshape(3,3)

print(matriz_1_9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [136]:
array = np.array([1,2,3])

print(matriz_1_9 - array)

[[0 0 0]
 [3 3 3]
 [6 6 6]]
